name: Test tag output

on:
  workflow_dispatch:
  push:
    tags:
      - "t*"



permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Set output
        id: settag
        run: echo "tag=${GITHUB_REF:11}" >> $GITHUB_OUTPUT
      - name: Echo output
        run: echo ${{steps.settag.outputs.tag}}
